# Package Overview
package_name: credit_g

# Data Files
training_data_file: credit-g.csv

# Variables
# The variable we are attempting to predict (cnt)
target: class_t

pipeline_name: credit_g
pipeline_save_file: credit_g_v

# Features that will go inside processing pipeline
features:
  - checking_status
  - duration
  - credit_history
  - purpose
  - credit_amount
  - savings_status
  - employment
  - installment_commitment
  - personal_status
  - other_parties
  - residence_since
  - property_magnitude           
  - age
  - other_payment_plans          
  - housing
  - existing_credits
  - job
  - num_dependents

 

unused_fields:  # Features to drop before pipeline
  - own_telephone
  - foreign_worker


# Features names

checking_status: checking_status
duration: duration
credit_history: credit_history
purpose: purpose
credit_amount: credit_amount
savings_status: savings_status
employment: employment
installment_commitment: installment_commitment
personal_status: personal_status
other_parties: other_parties
residence_since: residence_since
property_magnitude: property_magnitude
age: age
other_payment_plans: other_payment_plans
housing: housing
existing_credits: existing_credits
job: job
num_dependents: num_dependents



# Mappings for Ordinal categorical features

checking_mapping: 
  <0: 0
  0<=X<200: 1
  >=200: 2
  no checking : 3 

credit_mappings:
  critical/other existing credit: 0
  existing paid: 1
  delayed previously: 2
  no credits/all paid: 3
  all paid: 4

purpose_mappings:
  radio/tv: 0
  education: 1
  furniture/equipment: 2
  new car: 3
  used car: 4
  business: 5
  domestic appliance: 6
  repairs: 7
  others: 8
  retraining: 9

savings_mappings:
  no known savings: 0
  <100: 1
  100<=X<500: 2
  500<=X<1000: 3
  >=1000: 4


employment_mappings:
  <1: 0
  1<=X<4: 1
  4<=X<7: 2
  >=7: 3
  unemployed: 4

party_mappings:
  None: 0
  guarantor: 1
  co applicant: 2

personal_mappings:
  male single: 0
  female div/dep/mar: 1
  male div/sep: 2
  male mar/wid: 3

property_mappings:
  no known property: 0
  life insurance: 1
  car: 2
  real estate: 3

other_mapping:
  none: 0
  stores: 1
  bank: 2

housing_mappings:
  for free: 0
  rent: 1
  own: 2

job_mappings:
  unemp/unskilled non res: 0
  unskilled resident: 1
  skilled: 2
  high qualif/self emp/mgmt: 3

  
# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Alogrithm parameters
n_estimators: 100
max_depth: 10
